global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: user-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: ["tasks.chat-eda_user-service"]
        type: A
        port: 8081

  - job_name: search-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: ["tasks.chat-eda_search-service"]
        type: A
        port: 8081

  - job_name: ws-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: ["tasks.chat-eda_ws-service"]
        type: A
        port: 8081

  - job_name: postgres-exporter
    dns_sd_configs:
      - names: [ "tasks.chat-eda_postgres-exporter" ]
        type: A
        port: 9187

  - job_name: node-exporter
    dns_sd_configs:
      - names: [ "tasks.chat-eda_node-exporter" ]
        type: A
        port: 9100