spring.application.name=user-service

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.acks=1
spring.kafka.producer.compression-type=lz4
spring.kafka.producer.batch-size=${USER_KAFKA_BATCH_SIZE:131072}
spring.kafka.producer.linger-ms=${USER_KAFKA_LINGER_MS:10}
spring.kafka.producer.buffer-memory=${USER_KAFKA_BUFFER_MEMORY:67108864}
spring.kafka.consumer.properties.spring.json.trusted.packages=dto.*
spring.kafka.consumer.auto-offset-reset=earliest

management.endpoints.web.exposure.include=health,info,prometheus
management.server.port=8081