spring.application.name=user-service

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.consumer.properties.spring.json.trusted.packages=dto.*
spring.kafka.consumer.auto-offset-reset=earliest

management.endpoints.web.exposure.include=health,info,prometheus
management.server.port=8081