spring.application.name=ws_service

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=dto.*
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.max-poll-records=500
spring.kafka.consumer.fetch-min-bytes=65536
spring.kafka.consumer.fetch-max-wait=25ms
spring.kafka.listener.concurrency=4
app.kafka.ws-group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:ws-service}

management.endpoints.web.exposure.include=health,info,prometheus
management.server.port=8081