spring.application.name=ws_service

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}
app.websocket.executor.inbound.core-pool-size=${WS_INBOUND_EXECUTOR_CORE_POOL_SIZE:4}
app.websocket.executor.inbound.max-pool-size=${WS_INBOUND_EXECUTOR_MAX_POOL_SIZE:16}
app.websocket.executor.inbound.queue-capacity=${WS_INBOUND_EXECUTOR_QUEUE_CAPACITY:1000}
app.websocket.executor.outbound.core-pool-size=${WS_OUTBOUND_EXECUTOR_CORE_POOL_SIZE:8}
app.websocket.executor.outbound.max-pool-size=${WS_OUTBOUND_EXECUTOR_MAX_POOL_SIZE:32}
app.websocket.executor.outbound.queue-capacity=${WS_OUTBOUND_EXECUTOR_QUEUE_CAPACITY:5000}

management.endpoints.web.exposure.include=health,info,prometheus
management.server.port=8081